In [1]:
import pandas as pd

In [33]:
df2017 = pd.read_csv('~/Downloads/happiness_2017.csv')
df2017.head(1)

,Country,Region,Rank,HappinessScore,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government
0,Norway,Western Europe,1,7.537,7.578745,11.081789,0.950128,71.086586,0.953017,0.210104,0.249711,0.8491,0.202914,0.71716

In [14]:
df2012 = pd.read_csv('~/Downloads/happiness_2012.csv')

,country,Rank,Happiness Score,Life Ladder,Log GDP per capita,Social support,Healthy life expectancy at birth,Freedom to make life choices,Generosity,Perceptions of corruption,Positive affect,Negative affect,Confidence in national government,Democratic Quality,Delivery Quality,Standard deviation of ladder by country-year,Standard deviation/Mean of ladder by country-year,GINI index (World Bank estimate),"GINI index (World Bank estimate), average 2000-15","gini of household income reported in Gallup, by wp5-year"
0,Denmark,1,7.693,7.519909,10.699571,0.951437,70.044815,0.932628,0.127539,0.187408,0.773764,0.20857,0.534253,1.294512,2.01158,1.702373,0.226382,0.278,0.267091,0.365274

In [19]:
merged = df2017.merge(df2012, suffixes=('_2017', '_2012'), left_on='Country', right_on='country', how='left')

In [46]:
merged['Rank_diff'] = merged['Rank_2017']-merged['Rank_2012']

In [47]:
# Q-1: What is the name of the country with the largest positive change in their happiness rank?  What about the largest negative change?
merged[['Country', 'Rank_diff', 'HapinessScore_diff']].sort_values('Rank_diff', ascending=True).head(1)

     Country  Rank_diff  HapinessScore_diff
95  Bulgaria      -37.0               0.733

In [48]:
merged[['Country', 'Rank_diff', 'HapinessScore_diff']].sort_values('Rank_diff', ascending=False).head(1)

    Country  Rank_diff  HapinessScore_diff
99  Albania       41.0              -0.906

In [49]:
merged['HapinessScore_diff'] = merged['HappinessScore']-merged['Happiness Score']

In [50]:
# Q-2: Are the countries that with the largest change in rank the same as the countries with the largest change in score?
# Q-3: What is the name of the country with the largest positive change in their happiness score? 
merged[['Country', 'Rank_diff', 'HapinessScore_diff']].sort_values('HapinessScore_diff', ascending=True).head(3)

      Country  Rank_diff  HapinessScore_diff
120     Ghana       40.0              -0.971
121   Ukraine       40.0              -0.961
127  Zimbabwe       33.0              -0.952

In [51]:
merged[['Country', 'Rank_diff', 'HapinessScore_diff']].sort_values('HapinessScore_diff', ascending=False).head(3)

    Country  Rank_diff  HapinessScore_diff
89    Nepal      -34.0               0.806
49   Latvia      -33.0               0.804
52  Romania      -32.0               0.792

In [70]:
diff_col_names = []
for col_name in ['Life Ladder', 'Log GDP per capita', 'Social support', 'Generosity', 
                 'Negative affect', 'Confidence in national government', 'Positive affect', 'Perceptions of corruption',
                'Freedom to make life choices', 'Healthy life expectancy at birth']:
    new_col_name = col_name.split()[0] + "_d"
    diff_col_names.append(new_col_name)
    merged[new_col_name] = df2017[col_name] - df2012[col_name]

In [83]:
# or the five countries with the largest changes changes in ranking between 2012 and 2017 what are the factors that changed the most?
# # Q-5: What did you learn in the previous investigation? What were the factors that changed the most?
col_names_filter=['Country', 'Rank_diff', 'HapinessScore_diff'] + diff_col_names
merged_btm_5_rank = merged[col_names_filter].sort_values('HapinessScore_diff', ascending=True).head(5)
merged_btm_5_rank

,Country,Rank_diff,HapinessScore_diff,Life_d,Log_d,Social_d,Generosity_d,Negative_d,Confidence_d,Positive_d,Perceptions_d,Freedom_d,Healthy_d
120,Ghana,40.0,-0.971,1.526303,0.999549,-0.074655,0.142039,-0.052204,0.053198,0.157660,0.112323,0.161198,4.610867
121,Ukraine,40.0,-0.961,-0.001950,1.469575,0.034890,0.099043,0.125316,-0.375501,-0.083638,0.150045,-0.105344,15.929192
127,Zimbabwe,33.0,-0.952,-0.640970,0.591443,0.150421,-0.231940,0.023588,0.210836,-0.009188,-0.134577,0.115463,1.984032
99,Albania,41.0,-0.906,-0.084896,1.470274,0.055933,-0.007981,0.150639,-0.248074,-0.044267,0.111240,0.081929,8.108028
59,Cyprus,29.0,-0.845,0.527482,1.862274,0.043662,0.145816,0.079161,-0.543800,0.169061,0.036322,-0.044383,7.352158

In [84]:
merged_top_5_rank = merged[col_names_filter].sort_values('HapinessScore_diff', ascending=False).head(5)
merged_top_5_rank

,Country,Rank_diff,HapinessScore_diff,Life_d,Log_d,Social_d,Generosity_d,Negative_d,Confidence_d,Positive_d,Perceptions_d,Freedom_d,Healthy_d
89,Nepal,-34.0,0.806,-0.397195,-1.618452,-0.090212,0.320961,0.197795,0.133701,-0.190790,-0.068040,0.255003,10.680515
49,Latvia,-33.0,0.804,-0.017895,1.802048,0.068879,-0.162268,-0.081973,0.049378,0.055616,-0.157106,0.097102,2.572163
52,Romania,-32.0,0.792,0.175621,0.003594,-0.029979,-0.162506,0.053954,-0.463434,-0.133623,0.079040,-0.009485,2.264168
38,Bahrain,-35.0,0.775,0.101404,NaN,0.050675,NaN,0.149749,NaN,-0.007791,NaN,0.207663,-3.936005
95,Bulgaria,-37.0,0.733,0.633371,0.572994,0.327332,0.031065,-0.138362,-0.109132,0.093303,0.011347,0.121310,1.267494

In [94]:
import statsmodels.api as sm
from statsmodels.formula.api import ols
lm_expr = 'Rank_diff ~ Life_d + Log_d + Social_d + Generosity_d + Negative_d + Confidence_d + Positive_d + Perceptions_d + Freedom_d + Healthy_d'
mod = ols(lm_expr,
                data=merged).fit()
                
aov_table = sm.stats.anova_lm(mod, typ=2)
print(aov_table)
# TLDR: nothing stands out in general

                     sum_sq    df         F    PR(>F)
Life_d             0.696807   1.0  0.003303  0.954323
Log_d            489.237834   1.0  2.318782  0.131970
Social_d         118.055518   1.0  0.559534  0.456757
Generosity_d     365.477937   1.0  1.732212  0.192084
Negative_d       230.303718   1.0  1.091543  0.299441
Confidence_d     152.391480   1.0  0.722272  0.398069
Positive_d       852.376769   1.0  4.039909  0.047985
Perceptions_d      0.531961   1.0  0.002521  0.960085
Freedom_d        666.977628   1.0  3.161194  0.079408
Healthy_d         31.937635   1.0  0.151371  0.698317
Residual       16035.173046  76.0       NaN       NaN

In [95]:
mod = ols(lm_expr, data=merged_btm_5_rank).fit()
mod.summary()

/usr/local/lib/python3.7/site-packages/statsmodels/stats/stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 5 samples were given.
  "samples were given." % int(n), ValueWarning)
/usr/local/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1648: RuntimeWarning: divide by zero encountered in true_divide
  return 1 - (np.divide(self.nobs - self.k_constant, self.df_resid)
/usr/local/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1649: RuntimeWarning: invalid value encountered in double_scalars
  * (1 - self.rsquared))
/usr/local/lib/python3.7/site-packages/statsmodels/regression/linear_model.py:1665: RuntimeWarning: divide by zero encountered in double_scalars
  return self.ssr/self.df_resid

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Rank_diff   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                     0.000
Date:                Wed, 23 Oct 2019   Prob (F-statistic):                nan
Time:                        19:08:16   Log-Likelihood:                 147.89
No. Observations:                   5   AIC:                            -285.8
Df Residuals:                       0   BIC:                            -287.7
Df Model:                           4
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept        20.3278        inf          0        nan         nan         nan
Life_d            2.1041        inf          0        nan         nan         nan
Log_d             9.6140        inf          0        nan         nan         nan
Social_d         -4.2457        inf         -0        nan         nan         nan
Generosity_d     -7.7753        inf         -0        nan         nan         nan
Negative_d       10.3858        inf          0        nan         nan         nan
Confidence_d     22.6735        inf          0        nan         nan         nan
Positive_d      -16.1313        inf         -0        nan         nan         nan
Perceptions_d    17.6946        inf          0        nan         nan         nan
Freedom_d        24.6744        inf          0        nan         nan         nan
Healthy_d         0.7705        inf          0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   1.178
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.483
Skew:                          -0.197   Prob(JB):                        0.785
Kurtosis:                       1.529   Cond. No.                         120.
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
"""

In [96]:
mod = ols(lm_expr, data=merged_top_5_rank).fit()
mod.summary()

/usr/local/lib/python3.7/site-packages/statsmodels/stats/stattools.py:71: ValueWarning: omni_normtest is not valid with less than 8 observations; 4 samples were given.
  "samples were given." % int(n), ValueWarning)

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:              Rank_diff   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                    nan
Method:                 Least Squares   F-statistic:                     0.000
Date:                Wed, 23 Oct 2019   Prob (F-statistic):                nan
Time:                        19:08:43   Log-Likelihood:                 120.61
No. Observations:                   4   AIC:                            -233.2
Df Residuals:                       0   BIC:                            -235.7
Df Model:                           3
Covariance Type:            nonrobust
=================================================================================
                    coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------
Intercept       -19.8484        inf         -0        nan         nan         nan
Life_d          -14.0096        inf         -0        nan         nan         nan
Log_d            -3.6740        inf         -0        nan         nan         nan
Social_d         -5.0612        inf         -0        nan         nan         nan
Generosity_d      1.2919        inf          0        nan         nan         nan
Negative_d        1.7973        inf          0        nan         nan         nan
Confidence_d      7.8773        inf          0        nan         nan         nan
Positive_d       -0.2467        inf         -0        nan         nan         nan
Perceptions_d    -2.2242        inf         -0        nan         nan         nan
Freedom_d        -0.6643        inf         -0        nan         nan         nan
Healthy_d        -2.6189        inf         -0        nan         nan         nan
==============================================================================
Omnibus:                          nan   Durbin-Watson:                   0.600
Prob(Omnibus):                    nan   Jarque-Bera (JB):                0.572
Skew:                           0.000   Prob(JB):                        0.751
Kurtosis:                       1.148   Cond. No.                         22.0
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The input rank is higher than the number of observations.
"""

In [ ]:
# TLDR: can't say nothing. Jumbo coefficients / intercepts do not inspire confidence